### ISSUE TITLE
maternal mortality ratio & too big file size

### ISSUE THREAD

**Issue by oatkinsonr** [oatkinsonr/Soc_513_Final_Project#4]
hi @AaronGullickson I have put births in a data frame (currently it is in the input folder, I forgot it should be in my output so I will move that.) However, I am having a hard time figuring out how to calculate the maternal mortality ratio. I remember yesterday you should I would need to merge the data frames, but to calculate the MMR I need to first multiply the number of deaths by 100,000 then divide by the number of births (I think? Unsure). 

Also, I downloaded new files from IPUMS about occupation status and the file size is way too big. I remember several of us had this problem last term with our IPUMS data, but I can't remember what we did to fix it so it can be pushed to Git. I haven't pushed or committed them because they are so big. They are gz files.

**Comment by AaronGullickson** [comment]
Hi @oatkinsonr 

Leave the births in inputs - its raw data and thats where raw data goes.

Calculating the maternal mortality ratio is as easy as falling off a log. You just need to take deaths divided by births after merging. To merge:

```r
mm_data <- merge(mm_data, birth_data)
```

You can multiple by 100,000 if you want to get a measure that is maternal deaths per 100,000 births but its not necessary. I would recommend you look a the log of the MMR as your dependent variable so that all of your regression slopes are measured as log relative risks (which is similar to an odds ratio). 

On the IPUMS data, you will probably need to break the year range up into at least two different files and then combine them back later.
